using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO.Ports;
using System.IO;
using System.Net;

namespace SAKATAR_ZGİ_UPDATE
{
    public partial class Ana_Sayfa : System.Windows.Forms.UserControl
    {
        public string a;
        public int b;
        public Ana_Sayfa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the JsonDataSource asynchronously
        }

        public void Ana_Sayfa_Load(object sender, EventArgs e)
        {
            webBrowser1.Navigate("https://www.mgm.gov.tr/tahmin/il-ve-ilceler.aspx?il=%C4%B0stanbul&ilce=Atat%C3%BCrk%20Havaliman%C4%B1");
            webBrowser1.ScriptErrorsSuppressed = true;

            //  Form1 form1 = new Form1();
            //  a = form1.data;

            //b = int.Parse(a);
            //  linearScaleRangeBarComponent1.Value = b;
            //    linearScaleRangeBarComponent1.Value = form1.veri;


        }

        private void bunifuThinButton21_Click(object sender, EventArgs e)
        {

        }

        private void label4_Click(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox11_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox9_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox13_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox8_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox10_Click(object sender, EventArgs e)
        {

        }

        private void label17_Click(object sender, EventArgs e)
        {

        }

        private void label18_Click(object sender, EventArgs e)
        {

        }

        private void label19_Click(object sender, EventArgs e)
        {

        }

        private void gaugeControl1_Click(object sender, EventArgs e)
        {
            
        }

        private void label16_Click(object sender, EventArgs e)
        {

        }

        private void label20_Click(object sender, EventArgs e)
        {

        }

        private void label8_Click(object sender, EventArgs e)
        {
   

            }

        private void webBrowser1_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
        {

        }
    }
    }

